services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: think-us-api
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
    command: node server.js
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: think-us-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
